networks:
  openticketnet:
    driver: bridge

services:
  web:
    image: redsonbr/openticket:latest
    container_name: openticket_web
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      - db
      - redis
    networks:
      - openticketnet
  celery:
    image: redsonbr/openticket:latest
    container_name: openticket_celery
    env_file:
      - .env
    restart: unless-stopped
    command: celery -A OpenTIcket worker --loglevel=info
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      - db
      - redis
    networks:
      - openticketnet

  db:
    image: postgres:14
    container_name: openticket_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ti-chamados
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - openticketnet
  redis:
    image: redis:8.2.2
    container_name: openticket_redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    networks:
      - openticketnet
