# Generated by Django 5.1.5 on 2025-01-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_remove_ticket_state_ticket_assigned_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "Chamado", "verbose_name_plural": "Chamados"},
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[("low", "Baixa"), ("medium", "Média"), ("high", "Alta")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Novo"),
                    ("in_progress", "Em Progresso"),
                    ("resolved", "Resolvido"),
                    ("closed", "Fechado"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="department",
                to="tickets.department",
            ),
        ),
    ]
