# Generated by Django 5.1.5 on 2025-01-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_alter_ticket_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="image",
        ),
    ]
