# Generated by Django 5.1.5 on 2025-03-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_company_alter_ticket_status_ticket_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
