# Generated by Django 5.1.6 on 2025-03-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0010_alter_company_options_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "Chamado", "verbose_name_plural": "Chamados"},
        ),
    ]
