# Generated by Django 5.1.5 on 2025-03-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ticket_options_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
