# Generated by Django 5.1.5 on 2025-03-15 17:49

from django.db import migrations

def migrate_resolution_notes_to_comments(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")
    Comment = apps.get_model("tickets", "Comment")
    for ticket in Ticket.objects.all():
        if ticket.assigned_to is None and ticket.status != "resolved":
            continue
        if ticket.resolution_notes:
            timestamp = ticket.created_at
            if ticket.resolved_at:
                timestamp = ticket.resolved_at
            Comment.objects.create(
                ticket_id=ticket.id,
                author_id=ticket.assigned_to_id,
                text=ticket.resolution_notes,
            )
            # Clear the resolution_notes field after migrating
            ticket.resolution_notes = None
            ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_reply_text'),
    ]

    operations = [
        migrations.RunPython(migrate_resolution_notes_to_comments),
    ]
