# Generated by Django 5.1.5 on 2025-03-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_migrate_resolution_notes_to_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='resolution_notes',
        ),
    ]
