# Generated by Django 5.1.5 on 2025-03-22 11:11

from django.db import migrations


def move_comments_and_replies(apps, schema_editor):
    # Get the models
    OldTicketComment = apps.get_model('tickets', 'Comment')
    OldTicketReply = apps.get_model('tickets', 'Reply')
    NewComment = apps.get_model('comments', 'Comment')
    NewReply = apps.get_model('comments', 'Reply')

    # Move OldTicketComment to NewComment
    for old_comment in OldTicketComment.objects.all():
        NewComment.objects.create(
            id=old_comment.id,
            ticket_id=old_comment.ticket_id,
            author_id=old_comment.author_id,
            timestamp=old_comment.timestamp,
            text=old_comment.text,
        )

    # Move OldTicketReply to NewReply
    for old_reply in OldTicketReply.objects.all():
        NewReply.objects.create(
            id=old_reply.id,
            comment_id=old_reply.comment_id,
            author_id=old_reply.author_id,
            timestamp=old_reply.timestamp,
            text=old_reply.text,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_remove_ticket_resolution_notes'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(move_comments_and_replies),
    ]
