# Generated by Django 5.1.5 on 2025-03-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_move_comments_replies_to_new_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
